#ifndef __CONSTANTS__
#define __CONSTANTS__

// Framerate
#define PPL_TARGET_FRAMERATE 60

// Debug Console Constant
#define PPL_MAX_CONSOLE_LINES 31
#define PPL_MAX_BUFFER_SIZE 300

// Controller Constants
#define PPL_PLAYER_1 1
#define PPL_PLAYER_2 2
#define PPL_PLAYER_3 4
#define PPL_PLAYER_4 8

// KEY EVENT FLAGS
#define PPL_KEY_DOWN 0
#define PPL_KEY_UP 1
#define PPL_KEY_HELD 2

// KEY CODES
#define PPL_BUTTON_2 WPAD_BUTTON_2
#define PPL_BUTTON_1 WPAD_BUTTON_1
#define PPL_BUTTON_B WPAD_BUTTON_B
#define PPL_BUTTON_A WPAD_BUTTON_A
#define PPL_BUTTON_MINUS WPAD_BUTTON_MINUS
#define PPL_BUTTON_HOME WPAD_BUTTON_HOME
#define PPL_BUTTON_LEFT WPAD_BUTTON_LEFT
#define PPL_BUTTON_RIGHT WPAD_BUTTON_RIGHT
#define PPL_BUTTON_DOWN WPAD_BUTTON_DOWN
#define PPL_BUTTON_UP WPAD_BUTTON_UP
#define PPL_BUTTON_PLUS WPAD_BUTTON_PLUS

// THREADING
#define PPL_MAX_THREAD 13

#endif //__CONSTANTS__