#ifndef __BOARD_CONSTANTS__
#define __BOARD_CONSTANTS__

// Panel graphics constants
#define PANEL_IMAGE_SIZE 32
#define PANEL_IMAGE_SPACE -1

// Game modes constants
#define EASY_MODE_PANEL_NUM 5

// Panel types
#define PANEL_VOID_TYPE -1
#define PANEL_RED_TYPE 0
#define PANEL_CYAN_TYPE 1
#define PANEL_YELLOW_TYPE 2
#define PANEL_GREEN_TYPE 3
#define PANEL_PURPLE_TYPE 4
#define PANEL_GARBAGE_TYPE 5
#define PANEL_CONCRETE_GARBAGE_TYPE 6

// PANEL GRAPHCIS STYLE
#define PANEL_NORMAL_SPRITE 0
#define PANEL_BRIGHT_SPRITE 1
#define PANEL_FALL_FRAME_1 2
#define PANEL_FALL_FRAME_2 3
#define PANEL_FALL_FRAME_3 4
#define PANEL_FALL_FRAME_4 5
#define PANEL_FALL_FRAME_5 6
#define PANEL_FALL_FRAME_6 7
#define PANEL_FALL_FRAME_7 8
#define PANEL_FALL_FRAME_8 9
#define PANEL_FALL_FRAME_9 10
#define PANEL_FALL_FRAME_10 11

// Cursor Constants
#define CURSOR_WIDTH 68
#define CURSOR_HEIGHT 40
#define CURSOR_ANIMATION_LENGTH 11

// Animation Constants
#define FALL_DELAY 8

#endif // __BOARD_CONSTANTS__