/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _battleTheme_h_
#define _battleTheme_h_
//---------------------------------------------------------------------------------
extern const unsigned char battleTheme[];
extern const int battleTheme_size;
//---------------------------------------------------------------------------------
#endif //_battleTheme_h_
//---------------------------------------------------------------------------------
