/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _garbage_fall1_h_
#define _garbage_fall1_h_
//---------------------------------------------------------------------------------
extern const unsigned char garbage_fall1[];
extern const int garbage_fall1_size;
//---------------------------------------------------------------------------------
#endif //_garbage_fall1_h_
//---------------------------------------------------------------------------------
