/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _obstacles_h_
#define _obstacles_h_
//---------------------------------------------------------------------------------
extern const unsigned char obstacles[];
extern const int obstacles_size;
//---------------------------------------------------------------------------------
#endif //_obstacles_h_
//---------------------------------------------------------------------------------
