/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _blue_animation0003_h_
#define _blue_animation0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char blue_animation0003[];
extern const int blue_animation0003_size;
//---------------------------------------------------------------------------------
#endif //_blue_animation0003_h_
//---------------------------------------------------------------------------------
