/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0003_h_
#define _chainxunknown_0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0003[];
extern const int chainxunknown_0003_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0003_h_
//---------------------------------------------------------------------------------
