/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0040_h_
#define _chainxunknown_0040_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0040[];
extern const int chainxunknown_0040_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0040_h_
//---------------------------------------------------------------------------------
