/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0045_h_
#define _chainxunknown_0045_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0045[];
extern const int chainxunknown_0045_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0045_h_
//---------------------------------------------------------------------------------
