/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0007_h_
#define _chainxunknown_0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0007[];
extern const int chainxunknown_0007_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0007_h_
//---------------------------------------------------------------------------------
