/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0002_h_
#define _chainxunknown_0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0002[];
extern const int chainxunknown_0002_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0002_h_
//---------------------------------------------------------------------------------
