/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0009_h_
#define _chainxunknown_0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0009[];
extern const int chainxunknown_0009_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0009_h_
//---------------------------------------------------------------------------------
