/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0039_h_
#define _chainxunknown_0039_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0039[];
extern const int chainxunknown_0039_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0039_h_
//---------------------------------------------------------------------------------
