/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0014_h_
#define _chainxunknown_0014_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0014[];
extern const int chainxunknown_0014_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0014_h_
//---------------------------------------------------------------------------------
