/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chain_unknown_h_
#define _chain_unknown_h_
//---------------------------------------------------------------------------------
extern const unsigned char chain_unknown[];
extern const int chain_unknown_size;
//---------------------------------------------------------------------------------
#endif //_chain_unknown_h_
//---------------------------------------------------------------------------------
