/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0044_h_
#define _chainxunknown_0044_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0044[];
extern const int chainxunknown_0044_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0044_h_
//---------------------------------------------------------------------------------
