/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0004_h_
#define _chainxunknown_0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0004[];
extern const int chainxunknown_0004_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0004_h_
//---------------------------------------------------------------------------------
