/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0042_h_
#define _chainxunknown_0042_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0042[];
extern const int chainxunknown_0042_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0042_h_
//---------------------------------------------------------------------------------
