/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0041_h_
#define _chainxunknown_0041_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0041[];
extern const int chainxunknown_0041_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0041_h_
//---------------------------------------------------------------------------------
