/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0043_h_
#define _chainxunknown_0043_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0043[];
extern const int chainxunknown_0043_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0043_h_
//---------------------------------------------------------------------------------
