/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0013_h_
#define _chainxunknown_0013_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0013[];
extern const int chainxunknown_0013_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0013_h_
//---------------------------------------------------------------------------------
