/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0038_h_
#define _chainxunknown_0038_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0038[];
extern const int chainxunknown_0038_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0038_h_
//---------------------------------------------------------------------------------
