/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0005_h_
#define _chainxunknown_0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0005[];
extern const int chainxunknown_0005_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0005_h_
//---------------------------------------------------------------------------------
