/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0008_h_
#define _chainxunknown_0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0008[];
extern const int chainxunknown_0008_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0008_h_
//---------------------------------------------------------------------------------
