/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _chainxunknown_0011_h_
#define _chainxunknown_0011_h_
//---------------------------------------------------------------------------------
extern const unsigned char chainxunknown_0011[];
extern const int chainxunknown_0011_size;
//---------------------------------------------------------------------------------
#endif //_chainxunknown_0011_h_
//---------------------------------------------------------------------------------
