/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBox_Player2_0006_h_
#define _comboBox_Player2_0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBox_Player2_0006[];
extern const int comboBox_Player2_0006_size;
//---------------------------------------------------------------------------------
#endif //_comboBox_Player2_0006_h_
//---------------------------------------------------------------------------------
