/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0021_h_
#define _comboBoxPlayer_0021_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0021[];
extern const int comboBoxPlayer_0021_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0021_h_
//---------------------------------------------------------------------------------
