/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0010_h_
#define _comboBoxPlayer_0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0010[];
extern const int comboBoxPlayer_0010_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0010_h_
//---------------------------------------------------------------------------------
