/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0025_h_
#define _comboBoxPlayer_0025_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0025[];
extern const int comboBoxPlayer_0025_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0025_h_
//---------------------------------------------------------------------------------
