/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0006_h_
#define _comboBoxPlayer_0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0006[];
extern const int comboBoxPlayer_0006_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0006_h_
//---------------------------------------------------------------------------------
