/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboInterfaceAnimationP2_0012_h_
#define _comboInterfaceAnimationP2_0012_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboInterfaceAnimationP2_0012[];
extern const int comboInterfaceAnimationP2_0012_size;
//---------------------------------------------------------------------------------
#endif //_comboInterfaceAnimationP2_0012_h_
//---------------------------------------------------------------------------------
