/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0027_h_
#define _comboBoxPlayer_0027_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0027[];
extern const int comboBoxPlayer_0027_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0027_h_
//---------------------------------------------------------------------------------
