/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0017_h_
#define _comboBoxPlayer_0017_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0017[];
extern const int comboBoxPlayer_0017_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0017_h_
//---------------------------------------------------------------------------------
