/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboInterfaceAnimationP2_0006_h_
#define _comboInterfaceAnimationP2_0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboInterfaceAnimationP2_0006[];
extern const int comboInterfaceAnimationP2_0006_size;
//---------------------------------------------------------------------------------
#endif //_comboInterfaceAnimationP2_0006_h_
//---------------------------------------------------------------------------------
