/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBox_Player1_0021_h_
#define _comboBox_Player1_0021_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBox_Player1_0021[];
extern const int comboBox_Player1_0021_size;
//---------------------------------------------------------------------------------
#endif //_comboBox_Player1_0021_h_
//---------------------------------------------------------------------------------
