/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0024_h_
#define _comboBoxPlayer_0024_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0024[];
extern const int comboBoxPlayer_0024_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0024_h_
//---------------------------------------------------------------------------------
