/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0007_h_
#define _comboBoxPlayer_0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0007[];
extern const int comboBoxPlayer_0007_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0007_h_
//---------------------------------------------------------------------------------
