/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0022_h_
#define _comboBoxPlayer_0022_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0022[];
extern const int comboBoxPlayer_0022_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0022_h_
//---------------------------------------------------------------------------------
