/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0020_h_
#define _comboBoxPlayer_0020_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0020[];
extern const int comboBoxPlayer_0020_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0020_h_
//---------------------------------------------------------------------------------
