/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _combo_unknown_h_
#define _combo_unknown_h_
//---------------------------------------------------------------------------------
extern const unsigned char combo_unknown[];
extern const int combo_unknown_size;
//---------------------------------------------------------------------------------
#endif //_combo_unknown_h_
//---------------------------------------------------------------------------------
