/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboInterfaceAnimationP1_0003_h_
#define _comboInterfaceAnimationP1_0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboInterfaceAnimationP1_0003[];
extern const int comboInterfaceAnimationP1_0003_size;
//---------------------------------------------------------------------------------
#endif //_comboInterfaceAnimationP1_0003_h_
//---------------------------------------------------------------------------------
