/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0030_h_
#define _comboBoxPlayer_0030_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0030[];
extern const int comboBoxPlayer_0030_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0030_h_
//---------------------------------------------------------------------------------
