/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0003_h_
#define _comboBoxPlayer_0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0003[];
extern const int comboBoxPlayer_0003_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0003_h_
//---------------------------------------------------------------------------------
