/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboInterfaceAnimationP1_0007_h_
#define _comboInterfaceAnimationP1_0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboInterfaceAnimationP1_0007[];
extern const int comboInterfaceAnimationP1_0007_size;
//---------------------------------------------------------------------------------
#endif //_comboInterfaceAnimationP1_0007_h_
//---------------------------------------------------------------------------------
