/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0019_h_
#define _comboBoxPlayer_0019_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0019[];
extern const int comboBoxPlayer_0019_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0019_h_
//---------------------------------------------------------------------------------
