/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0012_h_
#define _comboBoxPlayer_0012_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0012[];
extern const int comboBoxPlayer_0012_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0012_h_
//---------------------------------------------------------------------------------
