/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0029_h_
#define _comboBoxPlayer_0029_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0029[];
extern const int comboBoxPlayer_0029_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0029_h_
//---------------------------------------------------------------------------------
