/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0014_h_
#define _comboBoxPlayer_0014_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0014[];
extern const int comboBoxPlayer_0014_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0014_h_
//---------------------------------------------------------------------------------
