/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0008_h_
#define _comboBoxPlayer_0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0008[];
extern const int comboBoxPlayer_0008_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0008_h_
//---------------------------------------------------------------------------------
