/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0015_h_
#define _comboBoxPlayer_0015_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0015[];
extern const int comboBoxPlayer_0015_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0015_h_
//---------------------------------------------------------------------------------
