/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0026_h_
#define _comboBoxPlayer_0026_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0026[];
extern const int comboBoxPlayer_0026_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0026_h_
//---------------------------------------------------------------------------------
