/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0016_h_
#define _comboBoxPlayer_0016_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0016[];
extern const int comboBoxPlayer_0016_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0016_h_
//---------------------------------------------------------------------------------
