/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _comboBoxPlayer_0013_h_
#define _comboBoxPlayer_0013_h_
//---------------------------------------------------------------------------------
extern const unsigned char comboBoxPlayer_0013[];
extern const int comboBoxPlayer_0013_size;
//---------------------------------------------------------------------------------
#endif //_comboBoxPlayer_0013_h_
//---------------------------------------------------------------------------------
