/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0010_h_
#define _dBlueFalling0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0010[];
extern const int dBlueFalling0010_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0010_h_
//---------------------------------------------------------------------------------
