/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0006_h_
#define _dBlueFalling0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0006[];
extern const int dBlueFalling0006_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0006_h_
//---------------------------------------------------------------------------------
