/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0008_h_
#define _dBlueFalling0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0008[];
extern const int dBlueFalling0008_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0008_h_
//---------------------------------------------------------------------------------
