/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBluedetect_h_
#define _dBluedetect_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBluedetect[];
extern const int dBluedetect_size;
//---------------------------------------------------------------------------------
#endif //_dBluedetect_h_
//---------------------------------------------------------------------------------
