/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0004_h_
#define _dBlueFalling0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0004[];
extern const int dBlueFalling0004_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0004_h_
//---------------------------------------------------------------------------------
