/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0002_h_
#define _dBlueFalling0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0002[];
extern const int dBlueFalling0002_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0002_h_
//---------------------------------------------------------------------------------
