/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0007_h_
#define _dBlueFalling0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0007[];
extern const int dBlueFalling0007_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0007_h_
//---------------------------------------------------------------------------------
