/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueblocked_h_
#define _dBlueblocked_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueblocked[];
extern const int dBlueblocked_size;
//---------------------------------------------------------------------------------
#endif //_dBlueblocked_h_
//---------------------------------------------------------------------------------
