/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0001_h_
#define _dBlueFalling0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0001[];
extern const int dBlueFalling0001_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0001_h_
//---------------------------------------------------------------------------------
