/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0003_h_
#define _dBlueFalling0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0003[];
extern const int dBlueFalling0003_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0003_h_
//---------------------------------------------------------------------------------
