/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dBlueFalling0009_h_
#define _dBlueFalling0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char dBlueFalling0009[];
extern const int dBlueFalling0009_size;
//---------------------------------------------------------------------------------
#endif //_dBlueFalling0009_h_
//---------------------------------------------------------------------------------
