/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGraydetect_h_
#define _dGraydetect_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGraydetect[];
extern const int dGraydetect_size;
//---------------------------------------------------------------------------------
#endif //_dGraydetect_h_
//---------------------------------------------------------------------------------
