/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGrayblocked_h_
#define _dGrayblocked_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGrayblocked[];
extern const int dGrayblocked_size;
//---------------------------------------------------------------------------------
#endif //_dGrayblocked_h_
//---------------------------------------------------------------------------------
