/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0006_h_
#define _dGreenFalling0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0006[];
extern const int dGreenFalling0006_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0006_h_
//---------------------------------------------------------------------------------
