/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0008_h_
#define _dGreenFalling0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0008[];
extern const int dGreenFalling0008_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0008_h_
//---------------------------------------------------------------------------------
