/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0007_h_
#define _dGreenFalling0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0007[];
extern const int dGreenFalling0007_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0007_h_
//---------------------------------------------------------------------------------
