/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0010_h_
#define _dGreenFalling0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0010[];
extern const int dGreenFalling0010_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0010_h_
//---------------------------------------------------------------------------------
