/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreendetect_h_
#define _dGreendetect_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreendetect[];
extern const int dGreendetect_size;
//---------------------------------------------------------------------------------
#endif //_dGreendetect_h_
//---------------------------------------------------------------------------------
