/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0002_h_
#define _dGreenFalling0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0002[];
extern const int dGreenFalling0002_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0002_h_
//---------------------------------------------------------------------------------
