/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0005_h_
#define _dGreenFalling0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0005[];
extern const int dGreenFalling0005_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0005_h_
//---------------------------------------------------------------------------------
