/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0001_h_
#define _dGreenFalling0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0001[];
extern const int dGreenFalling0001_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0001_h_
//---------------------------------------------------------------------------------
