/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0009_h_
#define _dGreenFalling0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0009[];
extern const int dGreenFalling0009_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0009_h_
//---------------------------------------------------------------------------------
