/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenblocked_h_
#define _dGreenblocked_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenblocked[];
extern const int dGreenblocked_size;
//---------------------------------------------------------------------------------
#endif //_dGreenblocked_h_
//---------------------------------------------------------------------------------
