/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0004_h_
#define _dGreenFalling0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0004[];
extern const int dGreenFalling0004_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0004_h_
//---------------------------------------------------------------------------------
