/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dGreenFalling0003_h_
#define _dGreenFalling0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char dGreenFalling0003[];
extern const int dGreenFalling0003_size;
//---------------------------------------------------------------------------------
#endif //_dGreenFalling0003_h_
//---------------------------------------------------------------------------------
