/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0006_h_
#define _dPurpleFalling0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0006[];
extern const int dPurpleFalling0006_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0006_h_
//---------------------------------------------------------------------------------
