/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0009_h_
#define _dPurpleFalling0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0009[];
extern const int dPurpleFalling0009_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0009_h_
//---------------------------------------------------------------------------------
