/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0001_h_
#define _dPurpleFalling0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0001[];
extern const int dPurpleFalling0001_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0001_h_
//---------------------------------------------------------------------------------
