/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0010_h_
#define _dPurpleFalling0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0010[];
extern const int dPurpleFalling0010_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0010_h_
//---------------------------------------------------------------------------------
