/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0002_h_
#define _dPurpleFalling0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0002[];
extern const int dPurpleFalling0002_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0002_h_
//---------------------------------------------------------------------------------
