/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpledetect_h_
#define _dPurpledetect_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpledetect[];
extern const int dPurpledetect_size;
//---------------------------------------------------------------------------------
#endif //_dPurpledetect_h_
//---------------------------------------------------------------------------------
