/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0007_h_
#define _dPurpleFalling0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0007[];
extern const int dPurpleFalling0007_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0007_h_
//---------------------------------------------------------------------------------
