/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0004_h_
#define _dPurpleFalling0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0004[];
extern const int dPurpleFalling0004_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0004_h_
//---------------------------------------------------------------------------------
