/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleblocked_h_
#define _dPurpleblocked_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleblocked[];
extern const int dPurpleblocked_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleblocked_h_
//---------------------------------------------------------------------------------
