/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0008_h_
#define _dPurpleFalling0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0008[];
extern const int dPurpleFalling0008_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0008_h_
//---------------------------------------------------------------------------------
