/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dPurpleFalling0003_h_
#define _dPurpleFalling0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char dPurpleFalling0003[];
extern const int dPurpleFalling0003_size;
//---------------------------------------------------------------------------------
#endif //_dPurpleFalling0003_h_
//---------------------------------------------------------------------------------
