/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0005_h_
#define _dRedFalling0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0005[];
extern const int dRedFalling0005_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0005_h_
//---------------------------------------------------------------------------------
