/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dReddetect_h_
#define _dReddetect_h_
//---------------------------------------------------------------------------------
extern const unsigned char dReddetect[];
extern const int dReddetect_size;
//---------------------------------------------------------------------------------
#endif //_dReddetect_h_
//---------------------------------------------------------------------------------
