/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedblocked_h_
#define _dRedblocked_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedblocked[];
extern const int dRedblocked_size;
//---------------------------------------------------------------------------------
#endif //_dRedblocked_h_
//---------------------------------------------------------------------------------
