/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0002_h_
#define _dRedFalling0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0002[];
extern const int dRedFalling0002_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0002_h_
//---------------------------------------------------------------------------------
