/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0008_h_
#define _dRedFalling0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0008[];
extern const int dRedFalling0008_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0008_h_
//---------------------------------------------------------------------------------
