/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0004_h_
#define _dRedFalling0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0004[];
extern const int dRedFalling0004_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0004_h_
//---------------------------------------------------------------------------------
