/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0010_h_
#define _dRedFalling0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0010[];
extern const int dRedFalling0010_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0010_h_
//---------------------------------------------------------------------------------
