/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0003_h_
#define _dRedFalling0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0003[];
extern const int dRedFalling0003_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0003_h_
//---------------------------------------------------------------------------------
