/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0009_h_
#define _dRedFalling0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0009[];
extern const int dRedFalling0009_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0009_h_
//---------------------------------------------------------------------------------
