/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0006_h_
#define _dRedFalling0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0006[];
extern const int dRedFalling0006_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0006_h_
//---------------------------------------------------------------------------------
