/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0001_h_
#define _dRedFalling0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0001[];
extern const int dRedFalling0001_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0001_h_
//---------------------------------------------------------------------------------
