/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dRedFalling0007_h_
#define _dRedFalling0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char dRedFalling0007[];
extern const int dRedFalling0007_size;
//---------------------------------------------------------------------------------
#endif //_dRedFalling0007_h_
//---------------------------------------------------------------------------------
