/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowblocked_h_
#define _dYellowblocked_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowblocked[];
extern const int dYellowblocked_size;
//---------------------------------------------------------------------------------
#endif //_dYellowblocked_h_
//---------------------------------------------------------------------------------
