/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0004_h_
#define _dYellowFalling0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0004[];
extern const int dYellowFalling0004_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0004_h_
//---------------------------------------------------------------------------------
