/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0011_h_
#define _dYellowFalling0011_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0011[];
extern const int dYellowFalling0011_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0011_h_
//---------------------------------------------------------------------------------
