/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0005_h_
#define _dYellowFalling0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0005[];
extern const int dYellowFalling0005_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0005_h_
//---------------------------------------------------------------------------------
