/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0008_h_
#define _dYellowFalling0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0008[];
extern const int dYellowFalling0008_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0008_h_
//---------------------------------------------------------------------------------
