/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0003_h_
#define _dYellowFalling0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0003[];
extern const int dYellowFalling0003_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0003_h_
//---------------------------------------------------------------------------------
