/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0002_h_
#define _dYellowFalling0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0002[];
extern const int dYellowFalling0002_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0002_h_
//---------------------------------------------------------------------------------
