/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0010_h_
#define _dYellowFalling0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0010[];
extern const int dYellowFalling0010_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0010_h_
//---------------------------------------------------------------------------------
