/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0006_h_
#define _dYellowFalling0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0006[];
extern const int dYellowFalling0006_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0006_h_
//---------------------------------------------------------------------------------
