/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0009_h_
#define _dYellowFalling0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0009[];
extern const int dYellowFalling0009_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0009_h_
//---------------------------------------------------------------------------------
