/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowdetect_h_
#define _dYellowdetect_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowdetect[];
extern const int dYellowdetect_size;
//---------------------------------------------------------------------------------
#endif //_dYellowdetect_h_
//---------------------------------------------------------------------------------
