/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0007_h_
#define _dYellowFalling0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0007[];
extern const int dYellowFalling0007_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0007_h_
//---------------------------------------------------------------------------------
