/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dYellowFalling0001_h_
#define _dYellowFalling0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char dYellowFalling0001[];
extern const int dYellowFalling0001_size;
//---------------------------------------------------------------------------------
#endif //_dYellowFalling0001_h_
//---------------------------------------------------------------------------------
