/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _garbage_transform_leaf_h_
#define _garbage_transform_leaf_h_
//---------------------------------------------------------------------------------
extern const unsigned char garbage_transform_leaf[];
extern const int garbage_transform_leaf_size;
//---------------------------------------------------------------------------------
#endif //_garbage_transform_leaf_h_
//---------------------------------------------------------------------------------
