/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _gray_animation0002_h_
#define _gray_animation0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char gray_animation0002[];
extern const int gray_animation0002_size;
//---------------------------------------------------------------------------------
#endif //_gray_animation0002_h_
//---------------------------------------------------------------------------------
