/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _gray_animation0008_h_
#define _gray_animation0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char gray_animation0008[];
extern const int gray_animation0008_size;
//---------------------------------------------------------------------------------
#endif //_gray_animation0008_h_
//---------------------------------------------------------------------------------
