/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0006_h_
#define _greenBreak0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0006[];
extern const int greenBreak0006_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0006_h_
//---------------------------------------------------------------------------------
