/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0004_h_
#define _greenBreak0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0004[];
extern const int greenBreak0004_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0004_h_
//---------------------------------------------------------------------------------
