/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0005_h_
#define _greenBreak0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0005[];
extern const int greenBreak0005_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0005_h_
//---------------------------------------------------------------------------------
