/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _green_animation0007_h_
#define _green_animation0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char green_animation0007[];
extern const int green_animation0007_size;
//---------------------------------------------------------------------------------
#endif //_green_animation0007_h_
//---------------------------------------------------------------------------------
