/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0001_h_
#define _greenBreak0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0001[];
extern const int greenBreak0001_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0001_h_
//---------------------------------------------------------------------------------
