/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0008_h_
#define _greenBreak0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0008[];
extern const int greenBreak0008_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0008_h_
//---------------------------------------------------------------------------------
