/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0002_h_
#define _greenBreak0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0002[];
extern const int greenBreak0002_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0002_h_
//---------------------------------------------------------------------------------
