/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0007_h_
#define _greenBreak0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0007[];
extern const int greenBreak0007_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0007_h_
//---------------------------------------------------------------------------------
