/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0009_h_
#define _greenBreak0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0009[];
extern const int greenBreak0009_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0009_h_
//---------------------------------------------------------------------------------
