/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0003_h_
#define _greenBreak0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0003[];
extern const int greenBreak0003_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0003_h_
//---------------------------------------------------------------------------------
