/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _greenBreak0010_h_
#define _greenBreak0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char greenBreak0010[];
extern const int greenBreak0010_size;
//---------------------------------------------------------------------------------
#endif //_greenBreak0010_h_
//---------------------------------------------------------------------------------
