/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _particle_trail_h_
#define _particle_trail_h_
//---------------------------------------------------------------------------------
extern const unsigned char particle_trail[];
extern const int particle_trail_size;
//---------------------------------------------------------------------------------
#endif //_particle_trail_h_
//---------------------------------------------------------------------------------
