/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0008_h_
#define _purpleBreak0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0008[];
extern const int purpleBreak0008_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0008_h_
//---------------------------------------------------------------------------------
