/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0006_h_
#define _purpleBreak0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0006[];
extern const int purpleBreak0006_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0006_h_
//---------------------------------------------------------------------------------
