/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0007_h_
#define _purpleBreak0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0007[];
extern const int purpleBreak0007_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0007_h_
//---------------------------------------------------------------------------------
