/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0010_h_
#define _purpleBreak0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0010[];
extern const int purpleBreak0010_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0010_h_
//---------------------------------------------------------------------------------
