/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0003_h_
#define _purpleBreak0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0003[];
extern const int purpleBreak0003_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0003_h_
//---------------------------------------------------------------------------------
