/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0009_h_
#define _purpleBreak0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0009[];
extern const int purpleBreak0009_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0009_h_
//---------------------------------------------------------------------------------
