/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purple_animation0003_h_
#define _purple_animation0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char purple_animation0003[];
extern const int purple_animation0003_size;
//---------------------------------------------------------------------------------
#endif //_purple_animation0003_h_
//---------------------------------------------------------------------------------
