/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0001_h_
#define _purpleBreak0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0001[];
extern const int purpleBreak0001_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0001_h_
//---------------------------------------------------------------------------------
