/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0011_h_
#define _purpleBreak0011_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0011[];
extern const int purpleBreak0011_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0011_h_
//---------------------------------------------------------------------------------
