/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0005_h_
#define _purpleBreak0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0005[];
extern const int purpleBreak0005_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0005_h_
//---------------------------------------------------------------------------------
