/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0004_h_
#define _purpleBreak0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0004[];
extern const int purpleBreak0004_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0004_h_
//---------------------------------------------------------------------------------
