/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _purpleBreak0002_h_
#define _purpleBreak0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char purpleBreak0002[];
extern const int purpleBreak0002_size;
//---------------------------------------------------------------------------------
#endif //_purpleBreak0002_h_
//---------------------------------------------------------------------------------
