/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _red_animation0008_h_
#define _red_animation0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char red_animation0008[];
extern const int red_animation0008_size;
//---------------------------------------------------------------------------------
#endif //_red_animation0008_h_
//---------------------------------------------------------------------------------
