/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _rockGarbage_h_
#define _rockGarbage_h_
//---------------------------------------------------------------------------------
extern const unsigned char rockGarbage[];
extern const int rockGarbage_size;
//---------------------------------------------------------------------------------
#endif //_rockGarbage_h_
//---------------------------------------------------------------------------------
