/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x3_electric_h_
#define _x3_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char x3_electric[];
extern const int x3_electric_size;
//---------------------------------------------------------------------------------
#endif //_x3_electric_h_
//---------------------------------------------------------------------------------
