/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x4_electric_h_
#define _x4_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char x4_electric[];
extern const int x4_electric_size;
//---------------------------------------------------------------------------------
#endif //_x4_electric_h_
//---------------------------------------------------------------------------------
