/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x4_fighting_h_
#define _x4_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char x4_fighting[];
extern const int x4_fighting_size;
//---------------------------------------------------------------------------------
#endif //_x4_fighting_h_
//---------------------------------------------------------------------------------
