/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x5_electric_h_
#define _x5_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char x5_electric[];
extern const int x5_electric_size;
//---------------------------------------------------------------------------------
#endif //_x5_electric_h_
//---------------------------------------------------------------------------------
