/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x5_fighting_h_
#define _x5_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char x5_fighting[];
extern const int x5_fighting_size;
//---------------------------------------------------------------------------------
#endif //_x5_fighting_h_
//---------------------------------------------------------------------------------
