/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x6_electric_h_
#define _x6_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char x6_electric[];
extern const int x6_electric_size;
//---------------------------------------------------------------------------------
#endif //_x6_electric_h_
//---------------------------------------------------------------------------------
