/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _x6_fighting_h_
#define _x6_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char x6_fighting[];
extern const int x6_fighting_size;
//---------------------------------------------------------------------------------
#endif //_x6_fighting_h_
//---------------------------------------------------------------------------------
