/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc10_fighting_h_
#define _xc10_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc10_fighting[];
extern const int xc10_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc10_fighting_h_
//---------------------------------------------------------------------------------
