/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc10_electric_h_
#define _xc10_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc10_electric[];
extern const int xc10_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc10_electric_h_
//---------------------------------------------------------------------------------
