/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc11_electric_h_
#define _xc11_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc11_electric[];
extern const int xc11_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc11_electric_h_
//---------------------------------------------------------------------------------
