/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc11_fighting_h_
#define _xc11_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc11_fighting[];
extern const int xc11_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc11_fighting_h_
//---------------------------------------------------------------------------------
