/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc1_fighting_h_
#define _xc1_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc1_fighting[];
extern const int xc1_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc1_fighting_h_
//---------------------------------------------------------------------------------
