/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc1_electric_h_
#define _xc1_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc1_electric[];
extern const int xc1_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc1_electric_h_
//---------------------------------------------------------------------------------
