/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc2_electric_h_
#define _xc2_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc2_electric[];
extern const int xc2_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc2_electric_h_
//---------------------------------------------------------------------------------
