/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc2_fighting_h_
#define _xc2_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc2_fighting[];
extern const int xc2_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc2_fighting_h_
//---------------------------------------------------------------------------------
