/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc3_electric_h_
#define _xc3_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc3_electric[];
extern const int xc3_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc3_electric_h_
//---------------------------------------------------------------------------------
