/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc3_fighting_h_
#define _xc3_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc3_fighting[];
extern const int xc3_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc3_fighting_h_
//---------------------------------------------------------------------------------
