/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc4_fighting_h_
#define _xc4_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc4_fighting[];
extern const int xc4_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc4_fighting_h_
//---------------------------------------------------------------------------------
