/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc4_electric_h_
#define _xc4_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc4_electric[];
extern const int xc4_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc4_electric_h_
//---------------------------------------------------------------------------------
