/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc5_electric_h_
#define _xc5_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc5_electric[];
extern const int xc5_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc5_electric_h_
//---------------------------------------------------------------------------------
