/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc6_electric_h_
#define _xc6_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc6_electric[];
extern const int xc6_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc6_electric_h_
//---------------------------------------------------------------------------------
