/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc6_fighting_h_
#define _xc6_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc6_fighting[];
extern const int xc6_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc6_fighting_h_
//---------------------------------------------------------------------------------
