/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc7_fighting_h_
#define _xc7_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc7_fighting[];
extern const int xc7_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc7_fighting_h_
//---------------------------------------------------------------------------------
