/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc7_electric_h_
#define _xc7_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc7_electric[];
extern const int xc7_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc7_electric_h_
//---------------------------------------------------------------------------------
