/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc8_electric_h_
#define _xc8_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc8_electric[];
extern const int xc8_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc8_electric_h_
//---------------------------------------------------------------------------------
