/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc8_fighting_h_
#define _xc8_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc8_fighting[];
extern const int xc8_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc8_fighting_h_
//---------------------------------------------------------------------------------
