/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc9_electric_h_
#define _xc9_electric_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc9_electric[];
extern const int xc9_electric_size;
//---------------------------------------------------------------------------------
#endif //_xc9_electric_h_
//---------------------------------------------------------------------------------
