/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _xc9_fighting_h_
#define _xc9_fighting_h_
//---------------------------------------------------------------------------------
extern const unsigned char xc9_fighting[];
extern const int xc9_fighting_size;
//---------------------------------------------------------------------------------
#endif //_xc9_fighting_h_
//---------------------------------------------------------------------------------
