/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0005_h_
#define _yellowBreak0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0005[];
extern const int yellowBreak0005_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0005_h_
//---------------------------------------------------------------------------------
