/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellow_animation0005_h_
#define _yellow_animation0005_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellow_animation0005[];
extern const int yellow_animation0005_size;
//---------------------------------------------------------------------------------
#endif //_yellow_animation0005_h_
//---------------------------------------------------------------------------------
