/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0009_h_
#define _yellowBreak0009_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0009[];
extern const int yellowBreak0009_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0009_h_
//---------------------------------------------------------------------------------
