/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0007_h_
#define _yellowBreak0007_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0007[];
extern const int yellowBreak0007_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0007_h_
//---------------------------------------------------------------------------------
