/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0008_h_
#define _yellowBreak0008_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0008[];
extern const int yellowBreak0008_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0008_h_
//---------------------------------------------------------------------------------
