/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0010_h_
#define _yellowBreak0010_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0010[];
extern const int yellowBreak0010_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0010_h_
//---------------------------------------------------------------------------------
