/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0001_h_
#define _yellowBreak0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0001[];
extern const int yellowBreak0001_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0001_h_
//---------------------------------------------------------------------------------
