/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0004_h_
#define _yellowBreak0004_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0004[];
extern const int yellowBreak0004_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0004_h_
//---------------------------------------------------------------------------------
