/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0006_h_
#define _yellowBreak0006_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0006[];
extern const int yellowBreak0006_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0006_h_
//---------------------------------------------------------------------------------
