/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0002_h_
#define _yellowBreak0002_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0002[];
extern const int yellowBreak0002_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0002_h_
//---------------------------------------------------------------------------------
