/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellow_animation0001_h_
#define _yellow_animation0001_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellow_animation0001[];
extern const int yellow_animation0001_size;
//---------------------------------------------------------------------------------
#endif //_yellow_animation0001_h_
//---------------------------------------------------------------------------------
