/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0003_h_
#define _yellowBreak0003_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0003[];
extern const int yellowBreak0003_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0003_h_
//---------------------------------------------------------------------------------
