/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _yellowBreak0011_h_
#define _yellowBreak0011_h_
//---------------------------------------------------------------------------------
extern const unsigned char yellowBreak0011[];
extern const int yellowBreak0011_size;
//---------------------------------------------------------------------------------
#endif //_yellowBreak0011_h_
//---------------------------------------------------------------------------------
